version: '3.9'

services:
  db:
    image: mysql
    platform: linux/x86_64

    ports:
      - 3306:3306
    volumes:
      - ./data-local/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=edek
      - MYSQL_DATABASE=starWars
